### ISSUE TITLE
Namespacing Variables

### ISSUE THREAD

**Issue by jethrolarson** [postcss/postcss-simple-vars#1]
Here's a feature idea I had:

    /* Define an object so you can namespace some variables. */
    $Button {
        font: 14px Arial;
        background-color: red;
        font-weight: bold;
        color: purple;
    }

    /* Use them with dot notation */
    .Button {
        background-color: $Button.background-color;
        font-weight: $Button.font-weight;
        color: $Button.color;
    }

I tried several syntaxes and I liked this best. It works well with typical syntax highlighting, is easy to implement, and looks like CSS.

I actually have a working implementation. I can send a pull request if you think this is a good idea.

**Comment by ai** [comment]
Why we need a namespace? Every variable works only in one file. So we haven’t really variable name conflict problems.

**Comment by jethrolarson** [comment]
Okay, for some reason I assumed that you could create vars in a separate file and import it, but I see the compiler explodes at that. Maybe what I'm seeking is better served by postcss-mixins, provided they work with postcss-import.

**Comment by ndelangen** [comment]
The need for this comes up when postcss-simple-vars is combined with postcss-import.
It's actually when I'm doing right now and I'm using variables like:

```postcss
$colors-brand: deepskyblue;
$colors-primary: hotpink;
$colors-dark: #333;

$widths-sm: 400px;
$widths-md: 700px;
$widths-lg: 900px;
$widhts-xl: 1200px;
$widths-xxl: 1500px;
$widths-wtf: 2500px;
```

**Comment by ai** [comment]
@ndelangen BTW, `postcss-simple-vars` also has a `variables` option to set project contants.

**Comment by ndelangen** [comment]
@ai I think that can be useful in most projects, but personally I'm looking for a less global-scope solution and declare imports of a certain group and then import that group of variables into something that needs those specific variables. 

Having a syntax as @jethrolarson has created would allow for a more declarative way to group variables together, which sounds like a good thing to me.

**Comment by ai** [comment]
@ndelangen agree, good idea for new PostCSS plugin ;)
