### ISSUE TITLE
How can I access variables in JS?

### ISSUE THREAD

**Issue by corysimmons** [postcss/postcss-simple-vars#10]
```css
$gutter: 30px;

.foo {
  column: 1/2;
}
```

```javascript
var postcss = require('postcss'),
    autoprefixer = require('autoprefixer'),
    simpleVars = require('postcss-simple-vars'),
    fs = require('fs');


var lost = postcss.plugin('lost', function() {
  return function (css, processor) {
    css.eachDecl('column', function (decl) {
      console.log($gutter); // how can I access this variable?
      decl.cloneBefore({ prop: 'float', value: 'left' });
      decl.cloneBefore({ prop: 'margin-right', value: '20px' });
      decl.cloneBefore({ prop: 'width', value: 'calc(100% * '+ decl.value +')' });
      decl.removeSelf();
    });
  };
});

var processor = postcss([autoprefixer, simpleVars, lost]);

processor.process(fs.readFileSync('app.css'), {
  from: 'app.css',
  to: 'app.out.css'
}).then(function (result) {

  console.log(result.css)
  fs.writeFileSync('app.out.css', result.css);

});
```

**Comment by corysimmons** [comment]
Also how can I create a default variable? I'm trying this:

```javascript
var postcss = require('postcss'),
    autoprefixer = require('autoprefixer'),
    simpleVars = require('postcss-simple-vars'),
    fs = require('fs');


module.exports = {
  gutter: '30px'
}

var lost = postcss.plugin('lost', function() {
  return function (css, processor) {
    css.eachDecl('column', function (decl) {
      console.log(gutter) // doesn't output anything
      decl.cloneBefore({ prop: 'float', value: 'left' });
      decl.cloneBefore({ prop: 'margin-right', value: '20px' });
      decl.cloneBefore({ prop: 'width', value: 'calc(100% * '+ decl.value +')' });
      decl.removeSelf();
    });
  };
});

var processor = postcss([autoprefixer, simpleVars, lost]);

processor.process(fs.readFileSync('app.css'), {
  from: 'app.css',
  to: 'app.out.css'
}).then(function (result) {

  console.log(result.css)
  fs.writeFileSync('app.out.css', result.css);

});

```

**Comment by ai** [comment]
PostCSS plugins should be maximum independent. You should use some special syntax for your lost plugin. For example, special property or at-rule.

**Comment by corysimmons** [comment]
What do you mean exactly?

**Comment by ai** [comment]
See postcss-flexgrid API for example. It creates same grid:  https://github.com/area17/postcss-flexgrid

**Comment by corysimmons** [comment]
I'm looking at it https://github.com/area17/postcss-flexgrid/blob/master/index.js#L4 but they seem to be using a settings object instead of postcss-simple-vars. I'd like to use postcss-simple-vars so they can override settings from their stylesheet.

**Comment by ai** [comment]
Use custom at-rule to override settings:

```css
@grid padding 20px;

.menu {
}
```

**Comment by corysimmons** [comment]
The syntax doesn't look as good:

```css
@gutter 20px; /* can I even do this or do I need a property as well? */

.foo {
  column: 1/2;
}
```

```css
$gutter: 20px;

.foo {
  column: 1/2;
}
```

**Comment by ai** [comment]
There is no languages, when user defined variables affects on libraries. You just think in Sassy way, but variables looks very strange.

**Comment by corysimmons** [comment]
I don't agree. I think people would like the ability to set global variables.

**Comment by ai** [comment]
What logical proof points do you have?

My points:

* Plugins should be independeble. Because less connections mean less bugs.
* There is no programmings languages except Sass, who uses global usser variables to control libraries. Sass has this API only because of limitations.

**Comment by corysimmons** [comment]
- People who want to use my grid system should be able to change global settings without having to know Node

**Comment by ai** [comment]
@corysimmons and what is problem with `@lost gutter 10px` at-rule?

**Comment by corysimmons** [comment]
1. It looks *absolutely* terrible

Taking all my questions and such to Gitter.
