### ISSUE TITLE
"Smart" vars detecting

### ISSUE THREAD

**Issue by TrySound** [postcss/postcss-simple-vars#11]
Hey guys!

What if:
At start variables will be replaced by variable name. Then will be detected undefined variables by regexp.

Everything like now, but the third test will invalid:
```js
test('$size: 10px; a { width: one$size }', 'a { width: one$size }');
```
This will work:
```js
test('$size: 10px; a { width: one$size }', 'a { width: one10px }');
```

**Comment by ai** [comment]
I think consistence `$()` notation is better. For example, we have no language with same interpolation in strings.
