### ISSUE TITLE
Removing CSS line if variable does not exist

### ISSUE THREAD

**Issue by jholt1** [postcss/postcss-simple-vars#110]
Is there a way to remove the line of CSS if the variable does not exist?

Was looking into using `unknown` option to return an empty string and use https://www.npmjs.com/package/postcss-discard-empty. However, so far, this does not work.

**Comment by ai** [comment]
Nope. We didn’t have this feature.

What is your use case?

**Comment by jholt1** [comment]
We are creating design tokens that are imported to use as variables. Based on the use of the design tokens config and themes - not all the tokens will exist. When the token does not exist, it indicates the style is not required.

**Comment by ai** [comment]
In this case it will be easier to write a simple custom PostCSS plugin to clean this variables and run it before `postcss-simple-vars`.

But you can also send PR to this plugin.

**Comment by jholt1** [comment]
Thanks @ai for the clarity, will give it a go
