### ISSUE TITLE
Question: simple vars in media query

### ISSUE THREAD

**Issue by inomn** [postcss/postcss-simple-vars#114]
Hi! I'm trying to migrate from SASS to PostCSS, and currently facing an issue with media queries.

// media.pcss
```
$media-m: "min-width: 600px";
```

// button.pcss
```
.root {
  @media ($media-m) {
    color: red;
  }
}
```

Output CSS file
```
@media ("min-width: 600px") {
  .root {
    width: 200px;
    color: red;
  }
}
```

The issue here is `"` around the media query rule and also WebStorm is not happy about this syntax
<img width="201" alt="Screenshot 2022-05-13 at 13 15 17" src="https://user-images.githubusercontent.com/6470994/168272293-82ecf977-13f0-4136-a9e5-d0ddbeb2bb11.png">

Any suggestions on how to fix this issue? Thanks in advance!

p.s. my plugins chain:
```
'postcss-simple-vars'
'postcss-calc'
'postcss-custom-media'
'postcss-mixins'
'postcss-nested-ancestors'
'postcss-atroot'
'postcss-current-selector'
'postcss-nested'
'postcss-mixins'
'autoprefixer'
'postcss-flexbugs-fixe
'postcss-easy-import'
```

**Comment by ai** [comment]
This syntax is non-standard. This is why WebStorm CSS linter print you an warning.

I recommend using CSS Custom Media from `postcss-preset-env` https://preset-env.cssdb.org/features/#custom-media-queries
