### ISSUE TITLE
[object Object] is not a PostCSS plugin error when used with Laravel Mix

### ISSUE THREAD

**Issue by tyssen** [postcss/postcss-simple-vars#123]
With this simple test case:

    const mix = require('laravel-mix');
    const theme = process.env.PREVIEW ? 'theme-preview' : 'theme';

    mix.setPublicPath('dist');

    mix.options({
        extractVueStyles: true,
        processCssUrls: false
    });

    mix.postCss('app/styles/test.css', 'dist', [
        require('postcss-simple-vars')({ variables: theme })
    ]);

I get:

> Error: [object Object] is not a PostCSS plugin

Not sure if I'm doing something wrong or if this is a bug?

**Comment by ai** [comment]
This error is coming from `laravel-mix`. Very likely that you are using PostCSS API in a wrong way. But it is better to ask Laravel community.
