### ISSUE TITLE
Preventing overrides

### ISSUE THREAD

**Issue by yksht** [postcss/postcss-simple-vars#17]
Hello :)
Can you add a special modificator that will prevent overrides? I think this is useful feature.

for example:
$foo: 50 !last; // foo equal 50
... a lot of CSS
...
...
$foo: 70; // foo still equal 50

**Comment by ai** [comment]
Like `!important`? For what case? :)

**Comment by ai** [comment]
PostCSS is not a porgramming language, like Sass templte language. So there is no scope and executed line.

**Comment by yksht** [comment]
I did small modification of your plugin and added this feature but used workaround :)
My project has difficult structure of CSS, a lot of files and variables and there are some situations when I need to prevent overriding...
just I tried to ask for this feature in the plugin. then I will not worry about updates :) it's ok if you will not add.

**Comment by ai** [comment]
I afraid that this changes will broke a current plugin simplicity. And it is a 100% non-PostCSS way :D.

But you can publish a form (`postcss-simple-vars-important`) and I will put a link to you.

**Comment by yksht** [comment]
ok, I understand :) thank you
