### ISSUE TITLE
Option to add messages notification on undefined variable for postcss-messages

### ISSUE THREAD

**Issue by benfrain** [postcss/postcss-simple-vars#18]
I like the fact that undefined vars fail. 

However, it would also be useful if this could be set to 'message' so that the info was pushed into the browser message area of postcss-messages.

e.g. `simpleVars({silent: message})` or `simpleVars({messages: true})`

**Comment by ai** [comment]
You mean to print just a warnings on undefined vars?

**Comment by benfrain** [comment]
Like, I have a `$text13: 13px;` but I don't have `$text14` and I do this:

`.thing {
    font-size: $text14;
}
`

As well as the build failing (e.g. Gulp) it would be good if postcss-messages also showed 'Undefined variable $text14 at line XXX' or similar up at the top of the page. Reason being sometimes (depending upon build setup) the build tool doesn't show a break.

**Comment by benfrain** [comment]
Arse, didn't mean to close!

**Comment by ai** [comment]
It is a `gulp-postcss` issue :). It just hide error message from plugin :).

/cc @w0rm

**Comment by w0rm** [comment]
I see some confusion between errors and messages in postcss: what kind of output should go where? 

In gulp-postcss all the errors are thrown without producing any result file, but messages are simply output in the console.

If you need to capture and output critical errors, there is a gulp way of doing it: https://www.npmjs.com/package/gulp-notify#notes-tip

**Comment by ai** [comment]
@w0rm postcss-simple-vars raise a error https://github.com/postcss/postcss-simple-vars/blob/master/index.js#L24

not warnings or messages

**Comment by w0rm** [comment]
@ai I get this, so there is no way of this ending up in postcss-messages.
