### ISSUE TITLE
plugins order

### ISSUE THREAD

**Issue by cmnstmntmn** [postcss/postcss-simple-vars#19]
i have a webpack config

`  module: {
    preLoaders: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'eslint-loader'
      }
    ],

    loaders: [
      {
        test: /\.css$/,
        loader: STYLE_LOADER + '!' + CSS_LOADER + '!postcss-loader'
      },
      {
        test: /\.scss$/,
        loader: STYLE_LOADER + '!' + CSS_LOADER + '!postcss-loader'
      },
      {
        test: /\.gif/,
        loader: 'url-loader?limit=10000&mimetype=image/gif'
      },
      {
        test: /\.jpg/,
        loader: 'url-loader?limit=10000&mimetype=image/jpg'
      },
      {
        test: /\.png/,
        loader: 'url-loader?limit=10000&mimetype=image/png'
      },
      {
        test: /\.svg/,
        loader: 'url-loader?limit=10000&mimetype=image/svg+xml'
      },
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'babel-loader'
      }
    ]
  },

  postcss: [autoprefixer(AUTOPREFIXER_BROWSERS), postcss_simple_vars, cssnext, postcss_mixins, postcss_import, postcss_nested, postcss_custom_media]
};
`

one **variables.scss**

and an **@import 'variables';** rule inside **app.scss**

and i get this error

`ERROR in ./~/css-loader!./~/postcss-loader!./src/components/Footer/Footer.scss
postcss-simple-vars: /Users/ctin/repos/goxgames/src/components/Footer/Footer.scss:12:5: Undefined variable $max-content-width
    padding: 20px 15px;
    max-width: $max-content-width;`

**Comment by ai** [comment]
PostCSS is not same as Sass :). There is not global namespace in PostCSS. So all variables works only local in current file. So if you didn’t define `$max-content-width` in `Footer.scss` it will not be used.

PostCSS has this behavour to split local and global variables.

There is two better ways to set global constants:

* [postcss-map](https://github.com/pascalduez/postcss-map)
* [`variables` option](https://github.com/postcss/postcss-simple-vars#variables) in `postcss-simple-vars`.

**Comment by ai** [comment]
BTW, use <code>```</code> around you code next time :).
