### ISSUE TITLE
Mathematical operations?

### ISSUE THREAD

**Issue by nicothin** [postcss/postcss-simple-vars#20]
$screen-md: 768px;
    $screen-sm-max: calc($screen-md - 1);
Is it possible?
width postcss-calc is impossible :(

**Comment by ai** [comment]
You variable is with px unit, but you use it with unitless value in calc().

calc($screenMd - 1px) is correct.

**Comment by nicothin** [comment]
I guess I'm doing something wrong :( 
my result: `@media (max-width: calc(768px - 1px))`
my grunt config:
<pre>
    postcss: {
      options: {
        // map: true,
        processors: [
          require('postcss-import'),
          require('postcss-nested'),
          require('postcss-calc'),
          require('postcss-simple-vars'),
        ]
      },
      dist: {
        src: 'css_src/style.css',
        dest: 'css/style.css'
      }
    },
</pre>

**Comment by ai** [comment]
You accept postcss-calc before postcss-simple-vars, so calc doesn't see a real value :-)

**Comment by nicothin** [comment]
Of course I tried it :)
the result is the same - there is no mathematical operation

**Comment by ai** [comment]
@nicothin OK, let’s try again:

1. Check that you use latest version of each plugin.
2. Write values with same units.
3. Use camelCase in names.

If it will not help, post here a input and output.

**Comment by nicothin** [comment]
the problem remains :(
grunt task:
<pre>postcss: {
  options: {
    // map: true,
    processors: [
      require('postcss-import'),
      require('postcss-nested'),
      // require('postcss-custom-properties'),
      require('postcss-css-variables'),
      require('postcss-simple-vars'),
      require('postcss-calc'),
      require('autoprefixer-core')({browsers: 'last 2 version'}),
      require("css-mqpacker"),
    ]
  },
  dist: {
    src: 'css_src/style.css',
    dest: 'css/style.css'
  }
},</pre>
source:
<pre>$screen1: 767px;
$screen2: calc($screen1 - 1px);

body {
  color: #000;

  @media (max-width: $screen2) {
    background-color: #0f0;
  }
}</pre>
result:
<pre>body {
  color: #000;
}

@media (max-width: calc(767px - 1px)) {

  body {
    background-color: #0f0;
  }
}</pre>
I missed what that little thing?

**Comment by ai** [comment]
You have same case here. You just clone your Sass methods, wiithout understanding of PostCSS ecosystem ;).

PostCSS source is not a code. Variables is just a shorcut, not a Turing complete statements.

Plugins are executed one by one. So in frist state all variable will be replaced to its value. In second step calc will be replaced to value. So you can’t use calc in variable and then use this variable somewhere. It is not a program.

And again, using a variables in CSS Media Quesris is a bad design. PostCSS have a CSS Custom Media for it.

`postcss-custom-media` will fix your style:

```css
$screen: 1024px;

@custom-media --small-viewport calc($sreen - 10px);

@media (--small-viewport) {
}
```

**Comment by ai** [comment]
Also there is no sense to use just a `css-mqpacker`.Try `cssnano` it has more optimisations.

**Comment by nicothin** [comment]
> using a variables in CSS Media Quesris is a bad design

and

> PostCSS can do the same work as preprocessors like Sass, Less, and Stylus. 

it's contradiction :(

**Comment by ai** [comment]
It can do same work "moving constants to some config file" but it is not mean one-to-one solution.

Of course, we can make one-to-one Turing complete variables, but it will promote bad result, when you combine code with styles.
