### ISSUE TITLE
Boolean variable

### ISSUE THREAD

**Issue by admdh** [postcss/postcss-simple-vars#24]
it would be great if there was ability to use boolean variables so using it with postcss conditionals was more fun.
For example:

```
$varible: true;

@if $variable{
  div{
    display: block;
  }
}
```

**Comment by ai** [comment]
It is possible, emprty string is a false in `@if`.

But seems like you try to write Sass code on PostCSS ;). Can you explain me your task? Maybe I will suggest you better way.

**Comment by admdh** [comment]
yes it's kind of sassy way.) i would like to make list of variable which will offer to include some css or not depending on situation so for for example if you don't need grid you just changing variable to false and it is not included and you don't need to delete it from import file or comment out.

**Comment by ai** [comment]
Ouh, bad bad way :).

CSS should be declarative and simple. It is source of all PostCSS benefits. There is no sense to rewrite styles to PostCSS in old Sass way :).
