### ISSUE TITLE
Add support for scss variable default statement

### ISSUE THREAD

**Issue by soilysound** [postcss/postcss-simple-vars#30]
Scss can do this with variables - 
```
$example: 'value' !default;
```

Whereby it will only set the value of $example if it doesn't already exist. This is an important function to allow cascading. 

Could this be supported in postcss-simple-vars?

**Comment by ai** [comment]
I think this behaviour of cascading is bad design.

What task you want to solve?

**Comment by soilysound** [comment]
Components that have certain values that we want to override with values set in a skin file: 

@import skin-for-red-website.css > sets $background:red
@import component.css > sets $background:grey !default

**Comment by ai** [comment]
https://github.com/postcss/postcss-simple-vars/issues/25#issuecomment-140525465
