### ISSUE TITLE
Variable interpolation - does not allow interpolating multiple variables.

### ISSUE THREAD

**Issue by BerraDev** [postcss/postcss-simple-vars#34]
``` CSS
$var1: value_of_var1;
$var2: value_of_var2;

$(var1)text // value_of_var1text
$(var1)$(var2) // Undefined variable $var1value_of_var2
```
According to this unittest this seems to be the wanted behaviour, but should it really be?
https://github.com/postcss/postcss-simple-vars/blob/master/test/test.js#L29

It seem that the variable interpolation should allow for concatenating multiple variables.

An obvious example is:

``` CSS
width: $(width)$(unit);
```

**Comment by ai** [comment]
Can’t reproduce:

```css
$var1: value_of_var1;
$var2: value_of_var2;

width: $(var1)text;
width: $(var1)$(var2);
```

Output:

```css
width: value_of_var1text;
width: value_of_var1value_of_var2;
```
