### ISSUE TITLE
Variable-like syntax in content property

### ISSUE THREAD

**Issue by KELiON** [postcss/postcss-simple-vars#35]
It is possible to have variable-like syntax in `content` property, i.e.

```css
.selector::before { 
  content: '$x';
}
```

Currently it will raise an error (undefined variable $x). I wanted to do PR with fix, but I think it is topic to discuss, what is proper behaviour in this case? I see two options: 

1) Use js-like syntax in strings in css, like `content: '$one'` will not be changed, but `content: '${one}'` will replace `${one}` to value of `$one`;
2) Use escapes for $ in this case, like `content: \$one` will be changed to `content: $one` and `content: $one` will be changed to variable value.

Any thoughts?

**Comment by ai** [comment]
Quick solution is to use `silent` mode.

Maybe we can add escaping? Like `\$x`?

**Comment by studiosciences** [comment]
The unicode escape syntax can address this...
    content:  "\u0024x";     /* "$x" */

**Comment by ai** [comment]
@studiosciences thank! I added this advice to docs 52e1dd8
