### ISSUE TITLE
Expose variables as json

### ISSUE THREAD

**Issue by duncanbeevers** [postcss/postcss-simple-vars#38]
I have a use-case where rather than trying to store css variables in JavaScript, I would like to store them as css and have postcss-simple-var export encountered variables.

**Comment by ai** [comment]
Maybe I can add a `callback`

**Comment by ai** [comment]
Is this API is OK?

```js
require('postcss-simple-vars')({
    onVariables: function (file, vars) {
        // vars will contains variables in file
    }
})
```

**Comment by ai** [comment]
There is a temporary solution:

```js
let vars = { };
let plugin = require('postcss-simple-vars')({
  variables: vars
});

postcss([plugin]).process(css);
// other files

vars // => { one: '1px', other variables from CSS }
```

**Comment by duncanbeevers** [comment]
I think a callback is more appropriate. In my straw-man implementation, `onVariables` is exactly the callback I used. I'll bake up a PR.
