### ISSUE TITLE
Fails silently with valid CSS

### ISSUE THREAD

**Issue by rnocc** [postcss/postcss-simple-vars#4]
We're trying to use postcss with the following CSS and JS, but it fails silently. If we pass an empty array to postcss, it copies the file as we would expect. Is there any common reason that this would be happening?

    $blue: #056ef0
    $column: 200px

    .menu_link {
        background: $blue;
        width: $column;
    }

    var gulp = require('gulp');
    var postcss = require('gulp-postcss');
    var postcssSimpleVars = require('postcss-simple-vars');

    gulp.src('./app/angular/styles/app/app.css')
      .pipe(postcss([postcssSimpleVars]))
      .pipe(gulp.dest('./public/styles'));

**Comment by ai** [comment]
You forget to put `;` after variables.

But issue is that it falls without any errors.
