### ISSUE TITLE
Multiple js variable files? 

### ISSUE THREAD

**Issue by pengx17** [postcss/postcss-simple-vars#41]
E.g., if I have two JS files containing two sets of variables:

```js
// config/colors.js

module.exports = {
    blue: '#056ef0'
}

// config/layout.js

module.exports = {
    wide: '1000px'
}
```

Can I inject the two set of variables?

```js
postcss([
    vars({
        variables: function () {
            return [ require('./config/colors'), require('./config/layout') ];
        }
    })
]
```

**Comment by ai** [comment]
Use ES6 descturctors:

```js
{
    ...require('./config/colors'),
    ...require('./config/layout')
}
```

**Comment by mariomurrent-softwaresolutions** [comment]
How would that look like in the example above? I can't get it to run with multiple files

**Comment by ai** [comment]
What error do you have?

**Comment by mariomurrent-softwaresolutions** [comment]
See my example:
` require('postcss-simple-vars')({
            variables: function variables() {
                return require('../src/file1')
            },
            unknown: function unknown(node, name, result) {
                node.warn(result, 'Unknown variable ' + name)
            }
        }),`

How exactly do I insert a second file after `return require('../src/file1')` so that e.g file1 and file2 are used

**Comment by ai** [comment]
```js
variables: {
    ...require('./config/colors'),
    ...require('./config/layout')
}
```

**Comment by mariomurrent-softwaresolutions** [comment]
Yeah, sorry - I missed a require in the second file. Thank you for you quick response and help :)
