### ISSUE TITLE
Question. How to use constants in css?

### ISSUE THREAD

**Issue by NXTaar** [postcss/postcss-simple-vars#43]
my `constants.js` file which i pass to the `variables` option
```
module.exports = {
    colors: {
        main:  "#562d91",
        side: "#d11774"
    }
    sizes: {
       general: '40px'
    }
};
```

what should i write in css to get this variables?

**Comment by ai** [comment]
Sorry, this plugin is for *simple* variables :). There are many other plugins with more complicated syntax and objects support:

https://github.com/postcss/postcss/blob/master/docs/plugins.md#language-extensions
