### ISSUE TITLE
Possible to use named ES6 exports?

### ISSUE THREAD

**Issue by kevinSuttle** [postcss/postcss-simple-vars#47]
See https://github.com/pascalduez/postcss-map/issues/76 for example.

**Comment by ai** [comment]
Sorry, the idea of ES named exports is to have control for imports. So if you want use a names from JS files, you should use `export default { name: 1 }`

**Comment by kevinSuttle** [comment]
So it's just exporting an anonymous object, then importing via:

`import name from 'Vars'` ?

**Comment by ai** [comment]
Yeap. I think it is the most ES6-ish way.
