### ISSUE TITLE
Could it be acceptable to use addition symbol in variable name?

### ISSUE THREAD

**Issue by benfrain** [postcss/postcss-simple-vars#59]
At present it's not possible to do this:

`$green+10: #14805e;`

Makes sense as it is effectively trying to add `green` to `10`. However, would it be possible/desirable to allow this symbol when following the `$` (with no whitespace)? For my use case it would be useful to do:

````
$green+10:
$green+20:
```` 

etc to define brightness shifts of a base colour.

**Comment by ai** [comment]
nope, because then you could write `calc($var+10)` ;)

Use just `$green10`

**Comment by benfrain** [comment]
👍
