### ISSUE TITLE
Reverse import

### ISSUE THREAD

**Issue by FezVrasta** [postcss/postcss-simple-vars#61]
Not sure if the title is clear.. well, actually I'm sure it is not.

Example:

```
// a.sss
$foo: 1

// b.sss
.b
  order: $foo

// c.sss
@import 'a'
@import 'b'
```

In this case, `$foo` in `b.sss` is undefined.
With Stylus it worked correctly (I'm converting a big Stylus code base).

Is it expected or am I doing something wrong somewhere else maybe?

**Comment by ai** [comment]
In PostCSS logic is different.

You import a.pcss to c.pcss.

Not to global state.

**Comment by FezVrasta** [comment]
So I have to change the imports of the whole code base, d'oh!

Thanks, it makes sense.

**Comment by natank** [comment]
Module.export a variables in a .js config file (e.g. colors.js), then  configure postcss simple vars accordingly.
For comple example and instructions refer to 'Variables' section in the post-css-simple-vars description (github.com):

`// config/colors.js

module.exports = {
    blue: '#056ef0'
}

// gulpfile.js

var colors = require('./config/colors');
var vars   = require('postcss-simple-vars')

gulp.task('css', function () {
     return gulp.src('./src/*.css')
        .pipe(postcss([ vars({ variables: colors }) ]))
        .pipe(gulp.dest('./dest'));
});`

**Comment by natank** [comment]
I break down the first step further:
1. You should create a java script config file
2. In this config file, create an object that will hold your variables as keys
3. In the config file, export this variables object, as shown in the 'colors' example given above
4. continue with the gulpfile as explained above.
is that fix the problem?
