### ISSUE TITLE
Variables = Parent

### ISSUE THREAD

**Issue by venelinn** [postcss/postcss-simple-vars#63]
Hi,
Is there a way to do something like this?

$baseColor: #444;
$baseText: $baseColor;

Thanks !

**Comment by ai** [comment]
Yeap. In this order it should work.

**Comment by venelinn** [comment]
But it doesn't 
`Message:
    postcss-simple-vars: /Users/venelin/Projects/YPG/postcss/sass/base/project/_variables.css:51:1: Undefined variable $baseColor

$baseColor: #444444;
$baseText: $baseColor;
`

**Comment by ai** [comment]
I tested with CSS:

```css
$baseColor: #444444;
$baseText: $baseColor;
color: $baseText;
```

and got:

```css
color: $baseText
```

Error was reported to 51 line in source code. So this 2 lines is not all that you have there. Maybe problem is different.

**Comment by ara4n** [comment]
hm, it's working for me...

```
sierra:vector-web matthew$ cat > test.css
.moo {
    $baseColor: #444444;
    $baseText: $baseColor;
    color: $baseText;
}
sierra:vector-web matthew$ node_modules/.bin/postcss -u postcss-simple-vars test.css
.moo {
    color: #444444;
}
```
