### ISSUE TITLE
Not compatible with postcss 5.0+ ?

### ISSUE THREAD

**Issue by sandiprb** [postcss/postcss-simple-vars#66]
Upgraded my postcss to 5.0 and unable compile build with postcsscli. 
Error:
`Your current PostCSS version is 5.2.15, but postcss-simple-vars uses 4.1.16`

**Comment by ai** [comment]
Update `postcss-simple-vars` too https://github.com/postcss/postcss-simple-vars/blob/master/package.json#L17

**Comment by sandiprb** [comment]
Done & working Thanks @ai
