### ISSUE TITLE
change identifier (as in the '$')

### ISSUE THREAD

**Issue by amci1203** [postcss/postcss-simple-vars#67]
I looked at the docs and through the code, but I didn't I see any option to change the default '$' to something, say for instance '@'. The specific reason I'm creating is issue is due to the module not playing nice with postcss-mixins which also uses the $ sign--all of my variables become undefined when I use mixins w/ paramaters. I don't know how much help I'd be, but I'd be glad to try.

**Comment by ai** [comment]
Take [PreCSS](https://github.com/jonathantneal/precss) plugin prepack. It fix plugins conflict.

**Comment by amci1203** [comment]
Oh, cool. Thank you
