### ISSUE TITLE
Nested variables from js file

### ISSUE THREAD

**Issue by geddski** [postcss/postcss-simple-vars#7]
I'm passing some variables into postcss-simple-vars:

```js
postcssSimpleVars({variables: require('./common/styles.js') })
```

Inside that file I'd like to namespace the styles like so:

```js
  module.exports = {
     layout: {
       header: '300px'
    },
    theme: {
       main: '#ccc'
    }
  }
```

And then use these variables in my css files:

```css
body{
  background: $theme.main
}


```

**Comment by ai** [comment]
Maybe postcss-map is better for this case.

**Comment by ai** [comment]
It makes code too diificult. Better do it in other plugin.

**Comment by geddski** [comment]
For anyone wanting nested variables I released a [webpack loader](https://github.com/geddski/jsvars-loader) for it.
