### ISSUE TITLE
runtime variable import

### ISSUE THREAD

**Issue by geddski** [postcss/postcss-simple-vars#8]
It would be really great if a css file could import variables from a js or json file at runtime, rather than at configuration time. This would allow postcss-simple-vars to work with webpack and live reloading when styles are changed, without having to restart webpack.

**Comment by ai** [comment]
We have [postcss-map](https://github.com/pascalduez/postcss-map) right now. But maybe we should add this feature too.

**Comment by ai** [comment]
Plugin now accepts a function as `variables` option: 425ed2c

**Comment by ai** [comment]
Released in 0.3 version.
