### ISSUE TITLE
JisonLexerError: Lexical error on line 1: Unrecognized text.

### ISSUE THREAD

**Issue by frederikhors** [postcss/postcss-simple-vars#95]
From `"postcss-simple-vars": "6.0.2"` to `"postcss-simple-vars": "6.0.3"` (the only upgrade in my package.json) I get this error during build:

```
Unknown error from PostCSS plugin. Your current PostCSS version is 8.2.4, but cssnano uses 7.0.35. Perhaps this is the source of the error below.
[!] (plugin postcss) JisonLexerError: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: 100vh - $my-custom-var
^..........^
```

**Comment by sampullman** [comment]
There is a potential incompatibility with plugins using PostCSS < 8, you can try the workaround here: #94 , otherwise the best option is to pin 6.0.2 until cssnano is updated.
